#!/bin/bash
set -e

cd $app_dir

. $app_dir/.genapp/control/env_exports

DART_VERSION=`cat $DART_SDK/version`
echo 'Dart build '$DART_VERSION
echo "Running app from $app_dir"

exec dart ${main_dart-main.dart}
